### ISSUE TITLE
Label text for both Measurement and Parameter objects needs to be on a readable (white/translucent) background

### ISSUE THREAD

**Issue by GullyAPCBurns** [SciKnowEngine/kefed.io#5]
At present the labels are placed on the background image making them hard to read.

**Comment by GSharayu** [comment]
Fixed. Please review

**Comment by GullyAPCBurns** [comment]
Looks good. 

1. Is it possible to put the text to the left of the parameter rather than underneath it?
2. Can you please do the same thing for the constant symbol as well?

**Comment by GSharayu** [comment]
1. Moved Label to left. But chances of getting it overwritten on Parameter Image are High unless Enter key is placed at right time. But Label can be adjusted. Please have look at changes made else we can revert them back.
2. Constant Symbol Label Text is fixed at bottom

**Comment by GullyAPCBurns** [comment]
OK, the left hand text doesn't work; it needs to be right justified *outside* the graphic.

Lets keep text for all elements except for Process and Entity under the graphic and see how it goes.

Leave text for Process and Entity inside the graphic.

**Comment by GSharayu** [comment]
Done for now.
Trying if we could separate out graphics.
